"use client";

import Link from "next/link";
import { useEffect,useMemo,useState,type CSSProperties } from "react";

const seriesList=["전체","헌터헌터","귀멸의칼날","나의히어로아카데미아","프리렌","진격의거인","치이카와","나루토","기타"];
const typeList=["전체","아크릴","지류","뱃지","피규어","키링","기타"];
const input:CSSProperties={height:36,border:"1px solid #d1d5db",borderRadius:7,padding:"0 9px",boxSizing:"border-box",background:"#fff"};

export default function SaleInventoryPage(){
 const [items,setItems]=useState<any[]>([]),[q,setQ]=useState(""),[series,setSeries]=useState("전체"),[type,setType]=useState("전체"),[stock,setStock]=useState("판매중"),[lineup,setLineup]=useState<string|null>(null),[msg,setMsg]=useState(""),[saving,setSaving]=useState<string|null>(null);
 async function load(){const r=await fetch("/api/sale-inventory",{cache:"no-store"});const j=await r.json();if(r.ok)setItems(j.items||[]);else setMsg(j.message||"조회 실패");}
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>items.filter(i=>{const text=[i.display_name,i.product_name,i.option_text,i.order_number].filter(Boolean).join(" ").toLowerCase();return(!q||text.includes(q.toLowerCase()))&&(series==="전체"||i.series_name===series)&&(type==="전체"||i.item_type===type)&&(stock==="전체"||(stock==="판매중"?i.stock_status!=="soldout":i.stock_status==="soldout"));}),[items,q,series,type,stock]);
 function edit(id:string,key:string,value:any){setItems(p=>p.map(i=>i.id===id?{...i,[key]:value}:i));}
 async function save(item:any,forceSoldout=false){setSaving(item.id);setMsg("");const next=forceSoldout?{...item,remaining_quantity:0,stock_status:"soldout"}:item;try{const r=await fetch("/api/sale-inventory",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({purchase_item_id:item.id,sale_price:next.sale_price,remaining_quantity:next.remaining_quantity,sold_quantity:next.sold_quantity,stock_status:next.stock_status,sale_memo:next.sale_memo,sold_out_at:next.sold_out_at})});const j=await r.json();if(!r.ok)throw new Error(j.message||"저장 실패");setItems(p=>p.map(i=>i.id===item.id?{...i,...j.item}:i));setMsg(forceSoldout?"재고 0 · 판매완료 처리했어.":"저장했어.");}catch(e){setMsg(e instanceof Error?e.message:"저장 실패");}finally{setSaving(null);}}
 return <main style={page}><header style={top}><div><h1 style={{margin:0}}>방송 판매재고</h1><p style={sub}>입고완료 상품 · 라인업 확인 · 판매가 · 판매/잔여수량 관리</p></div><div style={{display:"flex",gap:8}}><Link href="/" style={button}>메인</Link><Link href="/purchases" style={button}>매입관리</Link></div></header>
 <section style={filters}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="상품명 / 옵션 / 주문번호 검색" style={{...input,flex:"1 1 300px"}}/><select value={stock} onChange={e=>setStock(e.target.value)} style={input}>{["판매중","판매완료","전체"].map(x=><option key={x}>{x}</option>)}</select><select value={series} onChange={e=>setSeries(e.target.value)} style={input}>{seriesList.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} style={input}>{typeList.map(x=><option key={x}>{x}</option>)}</select><b>{filtered.length}개</b></section>
 {msg&&<div style={notice}>{msg}</div>}
 <section style={grid}>{filtered.map(i=><article key={i.id} style={{...card,opacity:i.stock_status==="soldout"?.55:1}}><div style={imageWrap}>{i.image_url?<img src={i.image_url} alt="" style={image}/>:<div style={noImage}>NO IMAGE</div>}<span style={badge}>{i.stock_status==="soldout"?"판매완료":`재고 ${i.remaining_quantity}`}</span></div><div style={body}><div style={tags}>{i.series_name&&<span style={tag}>{i.series_name}</span>}{i.item_type&&<span style={tag}>{i.item_type}</span>}</div><h2 style={name}>{i.display_name||i.product_name}</h2><div style={option}>{i.option_text||""}</div>
 <div style={numbers}><label>판매가<input type="number" value={i.sale_price??""} onChange={e=>edit(i.id,"sale_price",e.target.value)} placeholder="원" style={{...input,width:"100%"}}/></label><label>잔여수량<input type="number" min={0} value={i.remaining_quantity} onChange={e=>edit(i.id,"remaining_quantity",Number(e.target.value))} style={{...input,width:"100%"}}/></label><label>판매수량<input type="number" min={0} value={i.sold_quantity} onChange={e=>edit(i.id,"sold_quantity",Number(e.target.value))} style={{...input,width:"100%"}}/></label></div>
 <textarea value={i.sale_memo||""} onChange={e=>edit(i.id,"sale_memo",e.target.value)} placeholder="판매 메모" style={memo}/><div style={actions}>{i.lineup_image_url&&<button style={button} onClick={()=>setLineup(i.lineup_image_url)}>라인업 보기</button>}<button style={button} onClick={()=>void save(i)} disabled={saving===i.id}>저장</button>{i.stock_status!=="soldout"&&<button style={danger} onClick={()=>confirm("이 상품 재고를 0으로 만들고 판매완료 처리할까?")&&void save(i,true)}>재고삭제</button>}</div></div></article>)}</section>
 {lineup&&<div style={backdrop} onClick={()=>setLineup(null)}><div style={modal} onClick={e=>e.stopPropagation()}><button style={button} onClick={()=>setLineup(null)}>닫기</button><div style={{overflow:"auto",textAlign:"center"}}><img src={lineup} alt="라인업" style={{maxWidth:"100%",height:"auto"}}/></div></div></div>}
 </main>;
}
const page:CSSProperties={maxWidth:1500,margin:"0 auto",padding:"28px 22px 50px",background:"#f7f8fa",minHeight:"100vh",color:"#171717"};const top:CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:12,flexWrap:"wrap",marginBottom:16};const sub:CSSProperties={margin:"6px 0 0",color:"#6b7280",fontSize:14};const button:CSSProperties={display:"inline-flex",alignItems:"center",justifyContent:"center",height:34,padding:"0 10px",border:"1px solid #d1d5db",borderRadius:7,background:"#fff",color:"#27272a",fontSize:12,fontWeight:700,textDecoration:"none",cursor:"pointer"};const danger:CSSProperties={...button,borderColor:"#ef4444",color:"#b91c1c"};const filters:CSSProperties={display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",padding:12,background:"#fff",border:"1px solid #e5e7eb",borderRadius:10,marginBottom:14};const notice:CSSProperties={padding:10,background:"#fff",border:"1px solid #e5e7eb",borderRadius:8,marginBottom:12};const grid:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:14};const card:CSSProperties={background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,overflow:"hidden"};const imageWrap:CSSProperties={position:"relative",aspectRatio:"1 / 1",background:"#f4f4f5"};const image:CSSProperties={width:"100%",height:"100%",objectFit:"contain"};const noImage:CSSProperties={height:"100%",display:"flex",alignItems:"center",justifyContent:"center",color:"#aaa"};const badge:CSSProperties={position:"absolute",top:9,left:9,background:"rgba(17,24,39,.9)",color:"#fff",borderRadius:6,padding:"5px 8px",fontSize:11,fontWeight:800};const body:CSSProperties={padding:13};const tags:CSSProperties={display:"flex",gap:5,flexWrap:"wrap"};const tag:CSSProperties={padding:"3px 6px",borderRadius:5,background:"#f4f4f5",fontSize:10,fontWeight:700};const name:CSSProperties={fontSize:16,margin:"8px 0 4px"};const option:CSSProperties={fontSize:11,color:"#71717a",minHeight:30};const numbers:CSSProperties={display:"grid",gridTemplateColumns:"1.2fr .8fr .8fr",gap:6,marginTop:10,fontSize:10,fontWeight:700};const memo:CSSProperties={width:"100%",minHeight:55,boxSizing:"border-box",marginTop:8,padding:8,border:"1px solid #d1d5db",borderRadius:7,resize:"vertical"};const actions:CSSProperties={display:"flex",gap:6,justifyContent:"flex-end",marginTop:8,flexWrap:"wrap"};const backdrop:CSSProperties={position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,.7)",display:"flex",alignItems:"center",justifyContent:"center",padding:20};const modal:CSSProperties={width:"min(950px,95vw)",maxHeight:"92vh",overflow:"hidden",display:"flex",flexDirection:"column",gap:8,background:"#fff",padding:12,borderRadius:12};
